/* StudyQuest Live Multiplayer - Supabase Realtime */
const SUPABASE_URL='https://cfoyqyplnmxsxyxyfdbb.supabase.co';
const SUPABASE_ANON_KEY='sb_publishable_WcW00SpDEMZKGBas8dNRPA_dDjjVJ1s';
let sqLive=null,sqChannel=null,sqRoom=null;
function sqProfile(){try{return JSON.parse(localStorage.getItem('sqStudentProfile')||'{}')}catch{return{}}}
function sqId(){let p=sqProfile();let id=p.id||localStorage.getItem('sqLivePlayerId');if(!id){id='guest_'+crypto.randomUUID();localStorage.setItem('sqLivePlayerId',id)}return id}
function sqReady(){if(typeof supabase==='undefined'){alert('Supabase library did not load. Refresh the page.');return false}return true}
async function sqConnect(){if(!sqReady())return false;if(!sqLive)sqLive=supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);return true}
function sqName(){return sqProfile().name||'Student'}
async function createLiveRoom(){if(!await sqConnect())return;const code=Math.random().toString(36).slice(2,8).toUpperCase();const {data,error}=await sqLive.from('sq_rooms').insert({code,host_id:sqId(),name:document.getElementById('newName')?.value.trim()||'StudyQuest Live Room',status:'lobby'}).select().single();if(error){alert('Could not create room: '+error.message);return}sqRoom=data;await joinLiveRoom(code)}
async function joinLiveRoom(code){if(!await sqConnect())return;code=String(code||'').trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(code))return alert('Enter a valid 6-character room code.');const {data:room,error}=await sqLive.from('sq_rooms').select('*').eq('code',code).single();if(error||!room){alert('Room not found. Check the room code.');return}sqRoom=room;const {error:e}=await sqLive.from('sq_room_players').upsert({room_id:room.id,player_id:sqId(),player_name:sqName(),ready:false},{onConflict:'room_id,player_id'});if(e){alert('Could not join room: '+e.message);return}document.getElementById('setup')?.setAttribute('hidden',true);document.getElementById('liveLobby')?.removeAttribute('hidden');sqSubscribe();sqRenderRoom();sqRenderPlayers()}
function sqSubscribe(){if(sqChannel)sqLive.removeChannel(sqChannel);sqChannel=sqLive.channel('sq-room-'+sqRoom.id).on('postgres_changes',{event:'*',schema:'public',table:'sq_room_players',filter:'room_id=eq.'+sqRoom.id},()=>sqRenderPlayers()).on('postgres_changes',{event:'*',schema:'public',table:'sq_rooms',filter:'id=eq.'+sqRoom.id},p=>{sqRoom=p.new;sqRenderRoom()}).subscribe()}
async function sqRenderPlayers(){if(!sqRoom||!sqLive)return;const {data,error}=await sqLive.from('sq_room_players').select('*').eq('room_id',sqRoom.id).order('joined_at');if(error)return;const box=document.getElementById('livePlayerList');if(box)box.innerHTML=(data||[]).map((p,i)=>`<div class="mp-player">${i?'🎮':'👑'} ${escapeHtml(p.player_name)} ${p.ready?'✓ Ready':''}</div>`).join('')}
function sqRenderRoom(){const c=document.getElementById('liveRoomCode');if(c)c.textContent=sqRoom?.code||'—';const s=document.getElementById('liveRoomStatus');if(s)s.textContent=sqRoom?.status==='playing'?'MATCH LIVE':'WAITING FOR PLAYERS'}
async function toggleLiveReady(){if(!sqRoom||!sqLive)return;const {data}=await sqLive.from('sq_room_players').select('ready').eq('room_id',sqRoom.id).eq('player_id',sqId()).single();const {error}=await sqLive.from('sq_room_players').update({ready:!data?.ready}).eq('room_id',sqRoom.id).eq('player_id',sqId());if(error)alert(error.message);sqRenderPlayers()}
async function startLiveMatch(){if(!sqRoom||sqRoom.host_id!==sqId())return alert('Only the room host can start the match.');const {error}=await sqLive.from('sq_rooms').update({status:'playing',started_at:new Date().toISOString()}).eq('id',sqRoom.id);if(error)alert(error.message)}
async function leaveLiveRoom(){if(sqRoom&&sqLive)await sqLive.from('sq_room_players').delete().eq('room_id',sqRoom.id).eq('player_id',sqId());if(sqChannel)sqLive.removeChannel(sqChannel);sqRoom=null;sqChannel=null;document.getElementById('liveLobby')?.setAttribute('hidden',true);document.getElementById('setup')?.removeAttribute('hidden')}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
window.StudyQuestLive={create:createLiveRoom,join:joinLiveRoom,ready:toggleLiveReady,start:startLiveMatch,leave:leaveLiveRoom};
